# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY_NAME: rg-dimdim
  CLUSTER_NAME: aks-dimdim-prd
  CLUSTER_RESOURCE_GROUP: dimdim
  NAMESPACE: development
  APP_NAME: dimdim-backend

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
            docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
            
        # Set the target AKS cluster.
        - uses: Azure/k8s-set-context@v1
          with:
            kubeconfig: ${{ secrets.KUBE_CONFIG }}

        - uses: azure/k8s-create-secret@v1
          with:
            container-registry-url: ${{ env.REGISTRY_NAME }}.azurecr.io
            container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
            container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            secret-name: dimdim-k8s-secret
            arguments: --force true
            
        - uses: Azure/k8s-deploy@v1.4
          with:
            manifests: |
              kubefiles/app.deployment.yaml
              kubefiles/db.deployment.yaml
            images: |
              demo.azurecr.io/k8sdemo:${{ github.sha }}
            imagepullsecrets: |
              dimdim-k8s-secret
        
